from .cinemaos_standard import NODE_CLASS_MAPPINGS as STANDARD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STANDARD_DISPLAY
from .cinemaos_native import NODE_CLASS_MAPPINGS as NATIVE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as NATIVE_DISPLAY
from .cinemaos_cloud import NODE_CLASS_MAPPINGS as CLOUD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CLOUD_DISPLAY
from .cinemaos_vault import NODE_CLASS_MAPPINGS as VAULT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VAULT_DISPLAY

NODE_CLASS_MAPPINGS = {**STANDARD_MAPPINGS, **NATIVE_MAPPINGS, **CLOUD_MAPPINGS, **VAULT_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**STANDARD_DISPLAY, **NATIVE_DISPLAY, **CLOUD_DISPLAY, **VAULT_DISPLAY}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
